# Generated by Django 5.2.1 on 2025-06-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbdmsapp', '0008_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='mobno',
            new_name='mobilenumber',
        ),
        migrations.AddField(
            model_name='donorreg',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'requester'), (2, 'donor'), (1, 'admin')], default='1', max_length=50),
        ),
    ]
