# Generated by Django 5.2.1 on 2025-06-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbdmsapp', '0009_rename_mobno_bloodrequest_mobilenumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='mobilenumber',
            new_name='mobno',
        ),
    ]
